set_project("cautest-mcu-host-simulation")
set_languages("c11")
includes(os.files("tools/cautest/xmake.lua"))
target("firmware.simulated")
    set_kind("binary")
    set_default(false)
    add_rules("cautest.mcu-simulated")
    add_files("firmware.c")
    add_values("cautest.registry.suites", "mcu_smoke")
target_end()
