set_project("cautest-spi-behavioral-simulation")
set_languages("c11")
includes("tools/cautest/xmake.lua")
option("spi-fault")
    set_default(false)
    set_showmenu(true)
    set_description("Inject a wrong peripheral ID; device_identity MUST fail")
option_end()
target("firmware.spi")
    set_kind("binary")
    set_default(false)
    add_rules("cautest.mcu-simulated")
    add_files("spi_model.c", "test_spi.c")
    add_includedirs(".")
    add_values("cautest.registry.suites", "spi_protocol", "spi_transfer")
    if has_config("spi-fault") then add_defines("SPI_SIM_INJECT_RX_FAULT=1") end
target_end()
includes("ctest.lua")
