#ifndef CAUTEST_VERSION_H
#define CAUTEST_VERSION_H

/* 由 versions.json 生成；请运行 `npm run versions:sync`，不要手工修改。 */
#define CAUTEST_RELEASE_VERSION "0.2.1"
#define CAUTEST_C_API_MAJOR 2U
#define CAUTEST_C_API_MINOR 1U
#define CAUTEST_CTP_PROTOCOL_MAJOR 3U
#define CAUTEST_CTP_PROTOCOL_MINOR 1U
#define CAUTEST_KERNEL_ABI_MAJOR 3U
#define CAUTEST_KERNEL_ABI_MINOR 0U
#define CAUTEST_KERNEL_ABI_MAGIC 0xca7e57U
#define CAUTEST_PROBE_ABI_MAJOR 1U
#define CAUTEST_PROBE_ABI_MINOR 0U
#define CAUTEST_PROBE_ABI_MAGIC 0xca7e50U

#endif
