local toolroot = path.directory(path.directory(path.directory(os.scriptdir())))
local moduledir = path.join(toolroot, "adapters/xmake-test/modules")
rule("cautest.native")
    on_load(function (target)
        import("native", {rootdir = moduledir}).configure(target, toolroot)
    end)
    before_build(function (target)
        import("native", {rootdir = moduledir}).generate(target, toolroot)
    end)
rule_end()
