local toolroot = path.directory(path.directory(path.directory(os.scriptdir())))
local moduledir = path.join(toolroot, "adapters/xmake-test/modules")
rule("cautest.native")
    on_load(function (target)
        import("native", {rootdir = moduledir}).configure(target, toolroot)
    end)
    before_build(function (target)
        import("native", {rootdir = moduledir}).generate(target, toolroot)
    end)
rule_end()

-- GCC 覆盖率是构建选项；Job 的 coverage 声明负责本轮运行后的收集。
rule("cautest.gcov")
    on_load(function (target)
        import("native", {rootdir = moduledir}).configure_coverage(target)
    end)
    before_build(function (target)
        import("native", {rootdir = moduledir}).prepare_coverage(target)
    end)
    on_config(function (target)
        local _, compiler = target:tool("cc")
        assert(compiler == "gcc", "cautest.gcov currently requires Linux GCC and matching gcov")
    end)
rule_end()

-- Host simulation only: real MCU firmware targets remain owned by the application.
rule("cautest.mcu-simulated")
    on_load(function (target)
        import("native", {rootdir = moduledir}).configure(target, toolroot, true)
    end)
    before_build(function (target)
        import("native", {rootdir = moduledir}).generate(target, toolroot)
    end)
rule_end()

-- A distinct static CTP userspace artifact. It is never confused with the Driver .ko.
rule("cautest.driver-guest")
    on_load(function (target)
        import("native", {rootdir = moduledir}).configure(target, toolroot, false, true)
    end)
    before_build(function (target)
        import("native", {rootdir = moduledir}).generate(target, toolroot)
    end)
rule_end()
